volumes:
  wordpress:
  database:

services:
  mariadb:
    build: mariadb/
    image: mariadb_image
  wordpress-php:
    build: wordpress-php/
    image: wordpress-php_image
    volumes:
      - wordpress:/var/www/wordpress
  nginx:
    build: nginx/
    image: nginx_image
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "8080:80"