volumes:
  wordpress:

services:
  mariadb:
    build: mariadb/
    image: mariadb_image
# TODO: Exposure is not needed, because docker networks are automatically connected
    ports:
      - "3316:3306"
  wordpress-php:
    build: wordpress-php/
    image: wordpress-php_image
    volumes:
      - wordpress:/var/www/wordpress
  nginx:
    build: nginx/
    image: nginx_image
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "8080:80"