volumes:
  wordpress:
  database:

networks:
  inception_network:
    driver: bridge

services:
  mariadb:
    build: mariadb/
    image: mariadb_image
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception_network
  wordpress-php:
    build: wordpress-php/
    image: wordpress-php_image
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception_network
  nginx:
    build: nginx/
    image: nginx_image
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "${HOST_PORT}:443"
    restart: on-failure
    networks:
      - inception_network